# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image from github main branch
  jobs:
  - job: Build
    displayName: Build 
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Building a new container and pushing to docker hub
      inputs:
        repository: 'idanvak/sela-demos:tagname'
        command: buildAndPush
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
